language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

env:
    - JWT_SECRET=GWp7aej%t*7hh30A5hK9mZo*XrMGe*cq1tcbyuMTaqiGtpuoOF7OSUt95O@76*9u
